### ISSUE TITLE
Reggie! Bug

### ISSUE THREAD

**Issue by ghost** [Treeki/Reggie#1]
After the "choose a directory" dialog, reggie crashes with in the log:

Traceback (most recent call last):
  File "reggie.py", line 8458, in <module>
  File "reggie.py", line 8410, in main
  File "reggie.py", line 140, in SetGamePath
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 30: ordinal not in range(128)

I tested it on Linux and win, same error. I use a keyboard with specials characters, such as é è à ç... both on linux on windows.

**Comment by Treeki** [comment]
This bug has been fixed for the next release. I'll be releasing a new version shortly (hopefully later today).

As a temporary fix, you can copy your Stage folder into a path which doesn't include any special characters - this should fix it.
